name: Publish Docker image

on:
  workflow_dispatch: {}
  push:
    branches:
      - 'main'
      - 'dev'
      - 'fix-docker-action'
    paths:
      - 'code/src/**'
      - 'code/package.json'
      - 'code/Dockerfile'
      - '.github/workflows/publish-docker.yml'

jobs:
  docker-scan:
    name: ${{ github.event.repository.name }}-docker-scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
      - name: Build
        uses: docker/build-push-action@v6
        with:
          context: code
          push: false
          tags: user/app:latest
      #- name: Scan for vulnerabilities
      #  uses: crazy-max/ghaction-container-scan@dfa7e54dc32045120f06d0bc8d7724860f5db0ad
      #  with:
      #    image: user/app:latest
      #    severity_threshold: HIGH
  push-to-registry:
    name: Push Docker image to Docker Hub
    needs: docker-scan
    runs-on: ubuntu-latest
    # save forks from having issue trying to publish to Docker
    #  without the correct credentials
    if: github.repository_owner == 'finos'
    outputs:
      digest: ${{ steps.build_publish.outputs.digest }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4.2.2
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3.3.0
        with:
          username: finos
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.7
        with:
          images: finos/a11y-theme-builder
          tags: |
            type=ref,event=branch
            type=sha
      - name: Build and push Docker image
        id: build_publish
        uses: docker/build-push-action@v6
        with:
          context: code
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
